# Generated by Django 6.0.5 on 2026-05-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_map', '0002_remove_autismsupportplace_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autismsupportplace',
            name='x_position',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autismsupportplace',
            name='y_position',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
