# Generated by Django 6.0.5 on 2026-05-19 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('children', '0003_child_goals_child_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.JSONField(verbose_name='التصنيفات')),
                ('ai_summary', models.TextField(verbose_name='ملخص AI عن الطفل')),
                ('weekly_plan', models.JSONField(verbose_name='الخطة الأسبوعية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='children.child')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='assessment.assessmentsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'خطة دعم',
                'verbose_name_plural': 'خطط الدعم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('saturday', 'السبت'), ('sunday', 'الأحد'), ('monday', 'الاثنين'), ('tuesday', 'الثلاثاء'), ('wednesday', 'الأربعاء'), ('thursday', 'الخميس'), ('friday', 'الجمعة')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(default=15)),
                ('activity_id', models.IntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_activities', to='plans.supportplan')),
            ],
            options={
                'verbose_name': 'نشاط في الخطة',
                'verbose_name_plural': 'أنشطة الخطة',
                'ordering': ['day'],
            },
        ),
    ]
