# Generated by Django 6.0.5 on 2026-05-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='age',
        ),
        migrations.RemoveField(
            model_name='child',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='child',
            name='notes',
        ),
        migrations.AddField(
            model_name='child',
            name='birth_date',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='communication_type',
            field=models.CharField(choices=[('verbal', 'Verbal'), ('nonverbal', 'Nonverbal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='child',
            name='sensory_sensitivities',
            field=models.CharField(choices=[('sound', 'Sound'), ('touch', 'Touch'), ('light', 'Light'), ('none', 'None')], max_length=20),
        ),
    ]
