# Generated by Django 6.0.5 on 2026-05-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_remove_child_age_remove_child_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='child',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
