# Generated by Django 6.0.5 on 2026-05-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_commentlike'),
        ('community', '0004_report'),
    ]

    operations = [
    ]
