# Generated by Django 6.0.5 on 2026-05-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_merge_0004_commentlike_0004_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('solved', 'تم الحل')], default='pending', max_length=20),
        ),
    ]
