# Generated by Django 6.0.5 on 2026-05-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('visual', 'بصري'), ('sensory', 'حسي'), ('motor', 'حركي'), ('language', 'لغوي')], max_length=20)),
                ('description', models.TextField()),
                ('emoji', models.CharField(max_length=10)),
                ('level', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], default='easy', max_length=10)),
                ('html_file', models.CharField(max_length=100)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
