# Generated by Django 6.0.5 on 2026-05-18 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
