# Generated by Django 6.0.5 on 2026-05-17 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0002_remove_child_age_remove_child_goals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('ai_summary', models.TextField()),
                ('eye_contact_score', models.IntegerField()),
                ('attention_score', models.IntegerField()),
                ('repetitive_behavior_score', models.IntegerField()),
                ('interaction_level_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_analyses', to='children.child')),
            ],
        ),
    ]
