# Generated by Django 6.0.5 on 2026-05-17 08:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoanalysis',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
