# Generated by Django 6.0.5 on 2026-05-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0002_alter_videoanalysis_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoanalysis',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
