# Generated by Django 6.0.5 on 2026-05-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0003_alter_videoanalysis_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم النشاط')),
                ('description', models.TextField(verbose_name='وصف النشاط')),
                ('category', models.CharField(choices=[('focus', 'التركيز والانتباه'), ('eye_contact', 'التواصل البصري'), ('social', 'التفاعل الاجتماعي'), ('communication', 'التواصل اللغوي'), ('motor', 'المهارات الحركية'), ('behavior', 'السلوك والتصرفات')], max_length=50, verbose_name='التصنيف')),
                ('level', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], default='easy', max_length=10, verbose_name='المستوى')),
                ('age_min', models.PositiveIntegerField(default=2, verbose_name='العمر الأدنى')),
                ('age_max', models.PositiveIntegerField(default=12, verbose_name='العمر الأقصى')),
                ('emoji', models.CharField(blank=True, max_length=10, verbose_name='إيموجي')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نشاط',
                'verbose_name_plural': 'الأنشطة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResourceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الفيديو')),
                ('description', models.TextField(blank=True, verbose_name='وصف الفيديو')),
                ('video_file', models.FileField(upload_to='resource_videos/', verbose_name='ملف الفيديو')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='صورة مصغرة')),
                ('category', models.CharField(choices=[('focus', 'التركيز والانتباه'), ('eye_contact', 'التواصل البصري'), ('social', 'التفاعل الاجتماعي'), ('communication', 'التواصل اللغوي'), ('motor', 'المهارات الحركية'), ('behavior', 'السلوك والتصرفات')], max_length=50, verbose_name='التصنيف')),
                ('age_min', models.PositiveIntegerField(default=2, verbose_name='العمر الأدنى')),
                ('age_max', models.PositiveIntegerField(default=12, verbose_name='العمر الأقصى')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فيديو تعليمي',
                'verbose_name_plural': 'الفيديوهات التعليمية',
                'ordering': ['order'],
            },
        ),
    ]
