# Generated by Django 6.0.5 on 2026-05-18 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0004_activity_resourcevideo'),
        ('children', '0002_remove_child_age_remove_child_goals_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoanalysis',
            options={'verbose_name': 'تحليل فيديو', 'verbose_name_plural': 'تحليلات الفيديو'},
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_file',
            field=models.FileField(blank=True, null=True, upload_to='activities/', verbose_name='ملف النشاط'),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='ai_summary',
            field=models.TextField(verbose_name='تحليل الذكاء الاصطناعي'),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='attention_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.child', verbose_name='الطفل'),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='eye_contact_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='interaction_level_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='repetitive_behavior_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='video',
            field=models.URLField(verbose_name='رابط الفيديو'),
        ),
    ]
