# Generated by Django 6.0.5 on 2026-05-18 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0005_alter_videoanalysis_options_activity_activity_file_and_more'),
        ('children', '0002_remove_child_age_remove_child_goals_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoanalysis',
            options={},
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='ai_summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='attention_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_analyses', to='children.child'),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='eye_contact_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='interaction_level_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='repetitive_behavior_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
