# Generated by Django 6.0.5 on 2026-05-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0006_alter_videoanalysis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_file',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
