# Generated by Django 6.0.5 on 2026-05-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0007_activity_tag_alter_activity_activity_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('visual', 'بصري'), ('sensory', 'حسي'), ('motor', 'حركي'), ('language', 'لغوي')], max_length=50, verbose_name='التصنيف'),
        ),
    ]
