# Generated by Django 6.0.5 on 2026-05-19 05:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0008_alter_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10, verbose_name='مدة النشاط بالدقائق'),
        ),
        migrations.AlterField(
            model_name='resourcevideo',
            name='category',
            field=models.CharField(choices=[('visual', 'بصري'), ('sensory', 'حسي'), ('motor', 'حركي'), ('language', 'لغوي')], max_length=50, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='resourcevideo',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوا الفيديو'),
        ),
        migrations.AlterField(
            model_name='resourcevideo',
            name='video_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='ملف الفيديو'),
        ),
    ]
