# Generated by Django 6.0.5 on 2026-05-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0009_activity_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoanalysis',
            name='video',
            field=models.TextField(verbose_name='رابط الفيديو'),
        ),
    ]
