# Generated by Django 6.0.5 on 2026-05-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0010_alter_videoanalysis_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_file',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
