# Generated by Django 6.0.5 on 2026-05-19 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0003_child_goals_child_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('path', models.CharField(choices=[('video', 'مسار الفيديو'), ('questionnaire', 'مسار التقييم فقط')], max_length=20, verbose_name='المسار')),
                ('category', models.CharField(choices=[('visual', 'بصري'), ('sensory', 'حسي'), ('motor', 'حركي'), ('language', 'لغوي')], max_length=20, verbose_name='التصنيف')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='المصدر العلمي')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'سؤال تقييم',
                'verbose_name_plural': 'أسئلة التقييم',
                'ordering': ['path', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(choices=[('video', 'فيديو + تقييم'), ('questionnaire', 'تقييم فقط')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('analyzing', 'جاري التحليل'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='children.child')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جلسة تقييم',
                'verbose_name_plural': 'جلسات التقييم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.JSONField(verbose_name='التصنيفات المقترحة')),
                ('ai_summary', models.TextField(verbose_name='ملخص AI عن الطفل')),
                ('gemini_video_analysis', models.TextField(blank=True, verbose_name='تحليل Gemini للفيديو')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessment.assessmentsession')),
            ],
            options={
                'verbose_name': 'نتيجة تقييم',
                'verbose_name_plural': 'نتائج التقييم',
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('always', 'دائماً'), ('sometimes', 'أحياناً'), ('rarely', 'نادراً'), ('never', 'أبداً')], max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmentquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.assessmentsession')),
            ],
            options={
                'verbose_name': 'إجابة',
                'verbose_name_plural': 'الإجابات',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
